import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

// ✅ NEW IMPORTS
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ NEW FUNCTION (SERVER SIDE)


async function getUserFromCookie() {
  try {
    const cookieStore = cookies();
    const token = (await cookieStore).get("token")?.value;

    if (!token) return null;

    // ✅ Call backend /me route
    const res = await fetch("http://localhost:5000/auth/me", {
      method: "GET",
      headers: {
        Cookie: `token=${token}`, // 🔥 VERY IMPORTANT
      },
      cache: "no-store",
    });

    if (!res.ok) return null;

    const user = await res.json();

    return user;
  } catch (error) {
    console.error("Error fetching user from /me:", error);
    return null;
  }
}

// ✅ MAKE COMPONENT ASYNC
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ GET USER ON SERVER
  const user = await getUserFromCookie();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-950 dark:text-gray-200 transition-colors duration-300`}
      >
        {/* ✅ PASS USER HERE */}
        <StoreProvider user={user}>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}