import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-950 dark:text-gray-200 transition-colors duration-300`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}

// "use client";

// import "./globals.css";
// import { useState } from "react";
// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const [sidebarOpen, setSidebarOpen] = useState(false);

//   return (
//     <html lang="en">
//       <body className="bg-gray-50 dark:bg-gray-950 dark:text-gray-200">

//         <Navbar toggleSidebar={() => setSidebarOpen(!sidebarOpen)} />

//         <div className="flex">
//           <Sidebar open={sidebarOpen} />
//           <main className="flex-1 p-6">{children}</main>
//         </div>

//       </body>
//     </html>
//   );
// }
